POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjU1ODA5NDQsInVzZXJJZCI6MX0.9vbfxn55CEBKyul-wKXhtlyS4RkScUtqMJ9d6-Et5fY

{
  "name": "Test event 1",
  "description": "Another test event description 1",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
