POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzY1ODQzNTIyLCJ1c2VySWQiOjF9.xxlG3UpOgZ4us5KSG48I-qr8IBCkiSUswfZQyNI3nBw

{
  "name": "Test event 1",
  "description": "Another test event description 1",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
